<?php
include('../config/db_connect.php');
session_start();
if (!isset($_SESSION['matricula'])) { header('Location: login.php'); exit(); }
$isAdmin = isset($_SESSION['nivel']) && $_SESSION['nivel'] === 'admin';
$id = intval($_GET['id']);
$sql = "SELECT * FROM colaboradores WHERE id=$id";
$res = $conn->query($sql);
if ($res->num_rows==0){ echo 'Colaborador não encontrado'; exit(); }
$colab = $res->fetch_assoc();
$docs = $conn->query("SELECT * FROM documentos WHERE colaborador_id=$id ORDER BY data_upload DESC");
?>
<!DOCTYPE html><html lang='pt-br'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'><title>Perfil</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><style>:root{--eta-navy:#25499B;--eta-moss:#556049;--eta-light:#B4C6DC;--eta-bg:#E6E9F1;} body{background:var(--eta-bg)} .btn-eta{background:var(--eta-navy);color:white;border:none}</style></head><body><nav style='background:var(--eta-navy);color:white;padding:12px'><div style='margin-left:20px;'><strong>ETA Engenharia - RH</strong></div><div style='margin-right:20px;'>Usuário: <?php echo $_SESSION['matricula']; ?> <a href='../actions/logout.php' class='btn btn-light btn-sm ms-3'>Sair</a></div></nav><div class='container mt-4'><div class='card p-3'><h4><?php echo $colab['nome']; ?></h4><p><strong>Matrícula:</strong> <?php echo $colab['matricula']; ?></p><p><strong>Função:</strong> <?php echo $colab['funcao']; ?></p><p><strong>Status:</strong> <span class='badge bg-<?php echo ($colab['status']=='Ativo')?'success':'secondary'; ?>'><?php echo $colab['status']; ?></span></p></div><div class='mt-3'><h5>Documentos</h5><?php if($isAdmin): ?><form action='../actions/upload_documento.php' method='POST' enctype='multipart/form-data' class='mb-3'><input type='hidden' name='colaborador_id' value='<?php echo $colab['id']; ?>'><input type='hidden' name='nome_colab' value='<?php echo $colab['nome']; ?>'><input type='hidden' name='matricula' value='<?php echo $colab['matricula']; ?>'><div class='d-flex'><input type='file' name='documento' class='form-control me-2' required><button class='btn btn-eta'>Enviar</button></div></form><?php endif; ?><table class='table table-sm'><thead class='table-secondary'><tr><th>Arquivo</th><th>Data</th><th>Ações</th></tr></thead><tbody><?php if($docs->num_rows>0){ while($d=$docs->fetch_assoc()){ echo '<tr><td><a href="'.$d['caminho'].'" target="_blank">'.$d['nome_arquivo'].'</a></td><td>'.date('d/m/Y H:i',strtotime($d['data_upload'])).'</td><td>'; if($isAdmin) echo '<a class="btn btn-sm btn-outline-danger" href="../actions/deletar_documento.php?id='.$d['id'].'&colab='.$colab['id'].'" onclick="return confirm(\'Excluir?\')">Excluir</a>'; echo '</td></tr>'; } } else { echo '<tr><td colspan="3" class="text-center text-muted">Nenhum documento</td></tr>'; } ?></tbody></table></div></div></body></html>